### ISSUE TITLE
Make this ext works along with plupload.

### ISSUE THREAD

**Issue by colombiacultiva** [3D-I/phpBB-Exif-Image-Rotation#1]
**Is your feature request related to a problem? Please describe.**

The problem is that in order to use this extension I need to disable the resize function of "plupload.php". And then my disk space server quota would be quickly goes full, as most of my users take his/hers" photos with a smartphone, and pics usual size are 4-10 MB

**Describe the solution you'd like**

I would love this extension to works also with the resize function of phpBB, set in the ACP by the "Maximum image dimensions:"

**Describe alternatives you've considered**

I considered to use an external server like imagemagick, but I think my users prefer the attachment system, because of the files are saved and they won't be deleted.

**Additional context**
I think that would explain everything. Thank you so much!

**Comment by jhnmdahl** [comment]
I second this request.  Being able to manage image size in threads full of pictures is an important part of not only server space management, but server responsiveness and page load speed for clients.  Having this extension not work with maximum image size settings in place really hinders its usefulness.  I'd love an update that addresses this issue - thanks again!

**Comment by 3D-I** [comment]
Please read:
https://www.phpbb.com/community/viewtopic.php?p=15554281#p15554281
